// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBov7pRyW_aDMif5HFLHh5THefHmu3NeRE',
    appId: '1:546353065882:web:6131eeffd7ffb2ace7d423',
    messagingSenderId: '546353065882',
    projectId: 'tazaquiz-d6e1c',
    authDomain: 'tazaquiz-d6e1c.firebaseapp.com',
    storageBucket: 'tazaquiz-d6e1c.firebasestorage.app',
    measurementId: 'G-3THTLNW5YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEN_4mMYXOcqgRY-Y9Eq_PStSKyjubS1U',
    appId: '1:546353065882:android:11d423df375f8f75e7d423',
    messagingSenderId: '546353065882',
    projectId: 'tazaquiz-d6e1c',
    storageBucket: 'tazaquiz-d6e1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVwenrM3aRvOA5D3IuY3iqxSL_80hIVPs',
    appId: '1:546353065882:ios:de43f356b6264c27e7d423',
    messagingSenderId: '546353065882',
    projectId: 'tazaquiz-d6e1c',
    storageBucket: 'tazaquiz-d6e1c.firebasestorage.app',
    androidClientId: '546353065882-4h1f2hisqtjb43ucp2frmuinsptgosc1.apps.googleusercontent.com',
    iosBundleId: 'com.tazaquiz.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVwenrM3aRvOA5D3IuY3iqxSL_80hIVPs',
    appId: '1:546353065882:ios:de43f356b6264c27e7d423',
    messagingSenderId: '546353065882',
    projectId: 'tazaquiz-d6e1c',
    storageBucket: 'tazaquiz-d6e1c.firebasestorage.app',
    androidClientId: '546353065882-4h1f2hisqtjb43ucp2frmuinsptgosc1.apps.googleusercontent.com',
    iosBundleId: 'com.tazaquiz.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBov7pRyW_aDMif5HFLHh5THefHmu3NeRE',
    appId: '1:546353065882:web:d39d4687d9fbecdde7d423',
    messagingSenderId: '546353065882',
    projectId: 'tazaquiz-d6e1c',
    authDomain: 'tazaquiz-d6e1c.firebaseapp.com',
    storageBucket: 'tazaquiz-d6e1c.firebasestorage.app',
    measurementId: 'G-ZSJYZKQC60',
  );
}
